accounts/urls.py
from django.urls import path
from . import views

app_name = 'job'

urlpatterns = [
    
    path('signup/',views.signup, name='signup'),
    path('profile/',views.profile, name='profile'),
    path('profile/edit',views.projile_edit, name='profile_edit'),
    path('logout/',views.logout, name='logout'),
    
    
    
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    
    path('',views.send_message, name='signup'),   
]

job/urls.py
from django.urls import path
from . import views

app_name = 'job'

urlpatterns = [
    path('',views.home, name='home'),
    path('jobs/',views.job_list, name='list'),
    path('<str:slug>',views.job_detail, name='job_detail'),

]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('contact/', include('contact.urls',namespace='contact')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('', include('job.urls',namespace= 'jobs')),
    path('api-auth/', include('rest_framework.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_num = models.CharField(max_length=50)
    city = models.CharField(max_length=60 ,blank=True ,null=True)
    
    def __str__(self) :
        return str( self.user)
    
    

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
        

contact/models.py
from django.db import models

# Create your models here.



class message(models.Model):
    name = models.CharField(max_length=50)
    email = models.TextField(max_length=254)    
    messsage = models.TextField(max_length=300)
    def __str__(self):
        return self.name 
 

job/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify

# Create your models here.

def photo(inc,file_name):
    img_name,extention = file_name.split(".")
    return "jobs/%s.%s"%(inc.id,extention)
 
 
class job(models.Model): 
    Job_Type = (
        ('full time','full time'),
        ('part time','part time'),
    )
    owner = models.ForeignKey(User,related_name='job_owner',on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    #location
    job_type = models.CharField(max_length = 50,choices =Job_Type)
    description = models.TextField(max_length = 1000)
    published_at = models.DateTimeField(auto_now=True)
    Vacancy = models.IntegerField(default = 1)
    salary = models.IntegerField(default = 0)
    experience =  models.IntegerField(default = 1)
    category = models.ForeignKey('Category',on_delete=models.CASCADE)
    img = models.ImageField(upload_to = photo,blank=True,null=True)
    Country = models.CharField(max_length=50)
    slug = models.SlugField(blank=True,null=True)
    
    
    def save(self,*args, **kwargs):
        self.slug = slugify(self.title)
        super(job,self).save(*args, **kwargs)
        
        
    def __str__(self) :
        return self.title
    
    
class Category(models.Model):
    name = models.CharField(max_length = 50)
    photo_cat = models.ImageField(upload_to='cat_photo/%y/%m')
    def __str__(self) :
        return self.name
    
    
    


class apply(models.Model):
        name = models.CharField(max_length=50)
        email = models.EmailField(max_length=254)
        websit = models.URLField()
        cv = models.FileField(upload_to='aplly/')
        coverletter = models.TextField()
        published_at = models.DateTimeField(auto_now=True)
        titl = models.ForeignKey(job, related_name=("aplly_job"), on_delete=models.CASCADE)
        
        def __str__(self) :
           return self.name
        
        

    

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import User
from .models import Profile

class signupform(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']
        
        
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email']
        
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['city','phone_num']        

accounts/views.py
from django.shortcuts import render
from .forms import signupform ,UserForm,ProfileForm
from django.contrib.auth import authenticate,login,logout
from django.shortcuts import redirect,reverse
from .models import Profile
# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = signupform(request.POST)
        if form.is_valid:
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1'] 
            user = authenticate (username = username,password=password)
            login(request,user)
            return redirect('/accounts/login')
        
    else:
        form = signupform()
        
    return render(request,'registration/signup.html',{'form':form})        




def profile(requset):
    profile = Profile.objects.get(user=requset.user)
    
    return render(requset,'accounts/profile.html',{'profile':profile})



def projile_edit(request):
    profiles = Profile.objects.get(user = request.user)
    
    if request.method == 'POST':
        userform = UserForm(request.POST,instance=request.user)
        profileform = ProfileForm(request.POST,request.FILES,instance=profiles)
        if userform.is_valid() and profileform.is_valid() :
            userform.save()
            myprofile = profileform.save(commit=False)
            myprofile.user = request.user
            myprofile.save()
            return redirect(reverse('accounts:profile'))
    
    else:
        userform = UserForm(instance=request.user)
        profileform = ProfileForm(instance=profiles)
        
    
    return render(request,'accounts/profile_edit.html',{'userform':userform,'profileform':profileform})

def logout_user(request):
    logout(request)
    return redirect('home')

contact/views.py
from django.shortcuts import render
from . models import message
from django.conf import settings
# Create your views here.


def send_message(request):
    if request.method == 'POST':
        names = request.POST['name']
        emails = request.POST['email']
        messsage = request.POST['message']
        send = message(name = names ,email= emails ,messsage = messsage)
        send.save()

        
        
            
    return render(request,'contact/contact.html')

job/views.py
from django.urls import reverse
from django.shortcuts import render,redirect
from .models import job,Category
from django.core.paginator import Paginator
from .form import apply_form
from django.contrib.auth.decorators import login_required
from .filters import JobFilter
from django.db.models import Count
# Create your views here.
def home(request):
    
    joblist = Category.objects.annotate(total_jobs =Count('job'))
    joblisttow = job.objects.all()
    myffilter = JobFilter(request.GET,queryset=joblisttow)
    joblisttow = myffilter.qs
    context ={'jobb':joblist,'num':joblisttow,'myffilter':myffilter}

    return render(request,'job/index.html',context)

def job_list(request):
    job_list = job.objects.all()
    myfilter = JobFilter(request.GET,queryset=job_list)
    job_list = myfilter.qs
    
    paginator = Paginator(job_list, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    context = {'jobs':page_obj, 'myfilter' : myfilter}
    return render(request,'job/job_list.html',context)

@login_required
def job_detail(request,slug):
    job_detail = job.objects.get(slug=slug)
    if request.method == 'POST':
        form = apply_form(request.POST,request.FILES)
        if form.is_valid:
            my_form = form.save(commit=False)
            my_form.titl = job_detail
            my_form.save()
           
            
            
    else :
        form = apply_form()
        
    context = {'job':job_detail,'form':form}
    return render(request,'job/job_detail.html',context)

accounts/templates/accounts/profile.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job.title}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">

                <div class="col-lg-8  mx-auto">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Profile Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Name: <span>{{profile}}</span></li>
                                <li>Email: <span>{{profile.user.email}}</span></li>
                                <li>Phone Number: <span>{{profile.phone_num}}</span></li>
                                <li>Address: <span>{{profile.city}}</span></li>
                              
                            </ul>
                            <div class="p-3">
                                <a class="boxed-btn3 w-100" href="{% url 'accounts:profile_edit' %}">Edit Profile</a>
                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>

    <!-- footer start -->
  
{% endblock body %}

accounts/templates/accounts/profile_edit.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Add New Job</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">

                    <div class="apply_job_form white-bg">
                        <h4>Post New Job</h4>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form userform %}
                            {% bootstrap_form profileform %}
                            {% buttons %}
                              <button class="boxed-btn3 w-100" type="submit">Save</button>
                            {% endbuttons %}
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <!-- footer start -->
  
{% endblock body %}

contact/templates/contact/contact.html
{% extends "base.html" %}
{% block body %}
  
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>contact</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->
  <!-- ================ contact section start ================= -->
  <section class="contact-section section_padding">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <h2 class="contact-title">Get in Touch</h2>
        </div>
        <div class="col-lg-8">
          <form class="form-contact contact_form" method="post">
            {% csrf_token %}
            <div class="row">
              <div class="col-12">
                <div class="form-group">
                  <input class="form-control" name="name"  type="text" placeholder = 'Name'>
                </div>
              </div>
              <div class="col-sm-12">
                <div class="form-group">
                  <input class="form-control" name="email" type="email" placeholder = 'Enter email address'>
                </div>
              </div>
              <div class="col-12">
                <div class="form-group">
                  
                    <textarea class="form-control w-100" name="message"  cols="30" rows="9" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Message'" placeholder = 'Message'></textarea>
                </div>
              </div>



            </div>
            <div class="form-group mt-3">
              <button type="submit" class="button button-contactForm btn_4 boxed-btn">Send Message</button>
            </div>
          </form>
        </div>
        <div class="col-lg-4">
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-home"></i></span>
            <div class="media-body">
              <h3>{{myinfo.place}}</h3>
              <p>Rosemead, CA 91770</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-tablet"></i></span>
            <div class="media-body">
              <h3>{{myinfo.phone}}</h3>
              <p>Mon to Fri 9am to 6pm</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-email"></i></span>
            <div class="media-body">
              <h3>{{myinfo.email}}</h3>
              <p>Send us your query anytime!</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- ================ contact section end ================= -->
{% endblock body %}

job/templates/job/index.html
{% extends "base.html" %}
{% load static %}
{% block body %}
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>Welcome</h3>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- <div class="catagory_area">
        <div class="container">
            <div class="row cat_search">
                <div class="col-lg-3 col-md-4">
                    <div class="single_input">
                        <select class="wide">
                            <option data-display="Category">Category</option>
                            <option value="1">Category 1</option>
                            <option value="2">Category 2</option>
                            <option value="4">Category 3</option>
                        </select>
                    </div>
                </div>
                <div class="col-lg-3 col-md-12">
                    <div class="job_btn">
                        <a href="#" class="boxed-btn3">Find Job</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="popular_search d-flex align-items-center">
                        <span>Popular Search:</span>
                        <ul>
                            <li><a href="#">Design & Creative</a></li>
                            <li><a href="#">Marketing</a></li>
                            <li><a href="#">Administration</a></li>
                            <li><a href="#">Teaching & Education</a></li>
                            <li><a href="#">Engineering</a></li>
                            <li><a href="#">Software & Web</a></li>
                            <li><a href="#">Telemarketing</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div> -->
<!--/ catagory_area -->

<!-- popular_catagory_area_start  -->
<div class="popular_catagory_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section_title mb-40">
                    <h3>Popolar Categories</h3>
                </div>
            </div>
        </div>
        <div class="row">
            {% for joob in jobb %}
            <div class="col-lg-4 col-xl-3 col-md-6">
                <div class="single_catagory">

                    <img src="{% static 'img/1.png' %}" alt="job" class="img-category">

                    <!-- <a class="heart_mark_index" href="#"> <i class="fa fa-heart"></i> -->
                    <a>
                        <h4>{{joob.name}}</h4>
                    </a>
                    <p> <span>{{joob.total_jobs}}</span> Available position</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<!-- popular_catagory_area_end  -->


<!-- job_listing_area_end  -->

<!-- featured_candidates_area_start  -->



<!-- job_searcing_wrap  -->
<div class="job_searcing_wrap overlay">
    <div class="container">
        <div class="row">
            <div class="col-lg-5 offset-lg-1 col-md-6">
                <div class="searching_text">
                    <h3>Looking for a Job?</h3>
                    <p>We provide online instant cash loans with quick approval </p>
                    <a href="{%  url 'jobs:list' %}" class="boxed-btn3">Browse Job</a>
                </div>
            </div>
            <div class="col-lg-5 offset-lg-1 col-md-6">
                <div class="searching_text">
                    <h3>Looking for a Expert?</h3>
                    <p>We provide online instant cash loans with quick approval </p>

                </div>
            </div>
        </div>
    </div>
</div>
<!-- job_searcing_wrap end  -->

<!-- testimonial_area  -->

<!-- /testimonial_area  -->


<!-- footer start -->
{% endblock body %}

job/templates/job/job_list.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block body %}
  

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{jobs|length}} + Jobs Available</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        <div class="form_inner white-bg">
                            <h3>Filter</h3>
                            <form method="GET">
                                {% bootstrap_form myfilter.form %}
                                
                                <input type="submit" value="serch" class="boxed-btn3 w-100 mt-3"  >
                            </form>
                        </div>

                    </div>
                </div>
                <div class="col-lg-9">
                

                    <div class="job_lists m-0">
                        <div class="row">
                            {% for job in jobs %}
                              
                            
                            <div class="col-lg-12 col-md-12">
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="thumb">
                                            {% if job.img %}
                                                <img src="{{job.img.url}}" alt="Job" width="82" height="82">
                                            {% else %} 
                                                <img src="{% static 'img/job.png' %}" alt="Job" width="82" height="82">    
                                            {% endif %}
                                               
                                        </div>
                                        <div class="jobs_conetent">
                                            <a href="{% url 'jobs:job_detail' job.slug %}"><h4>{{job.title}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class="fa fa-map-marker"></i>{{job.Country}}</p>
                                                </div>
                                                <div class="location">
                                                    <p> <i class="fa fa-clock-o"></i>{{job.job_type}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                            <!-- <a class="heart_mark" href="#"> <i class="fa fa-heart"></i> </a> -->
                                            <a href="{% url 'jobs:job_detail' job.slug %}" class="boxed-btn3">Apply Now</a>
                                        </div>
                                        <div class="date">
                                            <p>Date line: {{job.published_at|date:'d M o'}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                           
                        </div>
                        {% if jobs.has_other_pages  %}
                          
                        
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="pagination_wrap">
                                        <ul>
                                            {% if jobs.has_previous %}                        
                                                <li><a href="?page={{jobs.previous.page_number}}"> <i class="ti-angle-left"></i> </a></li>
                                            {% endif %}
                                            {% for i in jobs.paginator.page_range %}                                           
                                                <li><a href="?page={{i}}"><span>{{i}}</span></a></li> 
                                            {% endfor %}
                                            {% if  jobs.has_next %}
                                                <li><a href="?page={{jobs.next.page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                            {% endif %} 

                                        </ul>
                                    </div>
                                </div>
                            </div>
                         {% endif %} 
                     </div>
                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->

    <!-- footer start -->
{% endblock body %}

templates/base.html
{% load static %}

<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Job Board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'css/responsive.css' %}"> -->
</head>

<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container-fluid ">
                    <div class="header_bottom_border">
                        <div class="row align-items-center">
                            <div class="col-xl-3 col-lg-2">
                                <div class="logo">
                                    <a href="">
                                        <img src="{% static 'img/logo.png' %}" width="50" height="50" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-7">
                                <div class="main-menu  d-none d-lg-block">
                                    <nav>
                                        <ul id="navigation">
                                            <li><a href="{% url 'jobs:home' %}">home</a></li>
                                            <li><a href="{%  url 'jobs:list' %}">Browse Job</a></li>
                                            <li><a href="{%  url 'contact:signup' %}">Contact</a></li>
                                            
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                            <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                                <div class="Appointment">
                                    {% if request.user.is_authenticated %}
                                        <div class="phone_num d-none d-xl-block">
                                            <a href="{% url 'logout' %}">log out</a>
                                        </div>

                                        <div class="phone_num d-none d-xl-block">
                                            <a class="boxed-btn3" href="{% url 'accounts:profile' %}">Profile</a>
                                        </div>
                                 
                                    {% else %}
                                        <div class="phone_num d-none d-xl-block">
                                            <a class = "boxed-btn3" href="{% url 'login' %}">Log in</a>
                                        </div>
                                    {% endif %}

                                    
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->
    {% block body %}
      
    {% endblock body %}

    <!-- footer start -->
    <footer class="footer">
        <p>© all rights reserved 2023</p>
        </footer>
    <!--/ footer end  -->

    <!-- link that opens popup -->
    <!-- JS here -->
    <script src="{%static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <script src="{%static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{%static 'js/popper.min.js' %}"></script>
    <script src="{%static 'js/bootstrap.min.js' %}"></script>
    <script src="{%static 'js/owl.carousel.min.js' %}"></script>
    <script src="{%static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{%static 'js/ajax-form.js' %}"></script>
    <script src="{%static 'js/waypoints.min.js' %}"></script>
    <script src="{%static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{%static 'js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{%static 'js/scrollIt.js' %}"></script>
    <script src="{%static 'js/jquery.scrollUp.min.js' %}"></script>
    <script src="{%static 'js/wow.min.js' %}"></script>
    <script src="{%static 'js/nice-select.min.js' %}"></script>
    <script src="{%static 'js/jquery.slicknav.min.js' %}"></script>
    <script src="{%static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{%static 'js/plugins.js' %}"></script>
    <!-- <script src="{%static 'js/gijgo.min.js' %}"></script> -->
    <script src="{%static 'js/range.js' %}"></script>



    <!--contact js-->
    <script src="{%static 'js/contact.js' %}"></script>
    <script src="{%static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{%static 'js/jquery.form.js' %}"></script>
    <script src="{%static 'js/jquery.validate.min.js' %}"></script>
    <script src="{%static 'js/mail-script.js' %}"></script>


    <script src="{%static 'js/main.js' %}"></script>


	<script>
        $( function() {
            $( "#slider-range" ).slider({
                range: true,
                min: 0,
                max: 24600,
                values: [ 750, 24600 ],
                slide: function( event, ui ) {
                    $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] +"/ Year" );
                }
            });
            $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) +
                " - $" + $( "#slider-range" ).slider( "values", 1 ) + "/ Year");
        } );
        </script>
</body>

</html>